### ISSUE TITLE
About  ModuleNotFoundError: No module named 'sgmllib'

### ISSUE THREAD

**Issue by Lin-xuejuan-an** [alireza-nasiri/SoundCLR#1]
Hello @alireza-nasiri  ，
        Thank you for sharing such excellent code .
        May I ask you a question？
         ‘ModuleNotFoundError: No module named 'sgmllib'’  error when I run code，Looking up the information, we know that the package above python3 is gone，How to solve this problem？

**Comment by alireza-nasiri** [comment]
I am not using that library and I run the code in python 3.7 which doesn't have that library. Maybe if you can copy the error code here to see which line of the code causes it, I can help you better.

**Comment by Lin-xuejuan-an** [comment]
Error：C:\Users\52937\Anaconda3\python.exe "F:/123/Contrastive Learning/code/SoundCLR-main/SoundCLR-main/train_contrastiveLoss.py"
Traceback (most recent call last):
  File "F:/123/Contrastive Learning/code/SoundCLR-main/SoundCLR-main/train_contrastiveLoss.py", line 21, in <module>
    import dataset_ESC50 as dataset
  File "F:\123\Contrastive Learning\code\SoundCLR-main\SoundCLR-main\dataset_ESC50.py", line 5, in <module>
    import transforms
  File "C:\Users\52937\Anaconda3\lib\site-packages\transforms\__init__.py", line 1, in <module>
    from .safe_html import safe_html, bodyfinder
  File "C:\Users\52937\Anaconda3\lib\site-packages\transforms\safe_html.py", line 1, in <module>
    from sgmllib import SGMLParser, SGMLParseError
ModuleNotFoundError: No module named 'sgmllib'

Process finished with exit code 1

1. import dataset_ESC50 as dataset
2. import transforms
3. from .safe_html import safe_html, bodyfinder
4. from sgmllib import SGMLParser, SGMLParseError
 These are four lines of code that indicate errors.

  Looking forward to your reply ！

**Comment by alireza-nasiri** [comment]
I updated couple of the lines including line 5 in dataset_ESC50.py. I changed "import transforms" to "from utils import transforms". I think this should solve the error that you are getting. I also made couple of updates in other import commands in the code.

Please let me know if changing the import commands take care of this issue.

**Comment by Lin-xuejuan-an** [comment]
Thank you very much. This problem has been solved ！

**Comment by alireza-nasiri** [comment]
Great, thanks for noticing this issue.
