### ISSUE TITLE
Ask if the code can run on other data sets

### ISSUE THREAD

**Issue by Lin-xuejuan-an** [alireza-nasiri/SoundCLR#2]
@alireza-nasiri 
   Hello，
   Sorry to disturb you again, I would like to ask if your code can be used on other data sets? (I am very sorry to tell you that my code level is limited, and I have not understood part of your code.) I understand that your data set is converted into a spectrogram for operation. I also have a processed spectrogram here. Form of data set. So what should I do next to run successfully? I would be very grateful if you could put forward some suggestions and methods.

**Comment by alireza-nasiri** [comment]
You can change the dataset files, to be more compatible with your dataset. Basically the dataset files are reading the data and make them ready to be input to the model. You can write your own data loader file for your dataset.
